# Generated by Django 4.1.5 on 2023-01-16 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0004_createpost_helpful_createpost_insightful_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='helpful',
        ),
        migrations.RemoveField(
            model_name='createpost',
            name='insightful',
        ),
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 16, 12, 10, 21, 923829)),
        ),
        migrations.DeleteModel(
            name='HelpPost',
        ),
    ]
