# Generated by Django 4.1.5 on 2023-01-18 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0005_remove_createpost_helpful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 23, 4, 48, 272040)),
        ),
    ]
